// ============================================================================
// Route Configuration
// Source of Truth: BankMate AI Frontend Blueprint · Phase 1 §8 (Route Hierarchy)
//   + Section 2 (Routing & Navigation Architecture)
// Centralized route path constants — maps EXACTLY to approved blueprint.
// ============================================================================

export const ROUTES = {
  // ── Public (no auth · BlankLayout) ───────────────────────────────────
  ROOT: '/',
  ABOUT: '/about',
  PUBLIC_PRODUCTS: '/products',
  PUBLIC_PRODUCT_DETAIL: '/products/:productId',
  CONTACT: '/contact',
  HELP: '/help',
  HELP_ARTICLE: '/help/:articleId',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  SITEMAP: '/sitemap',

  // ── Auth (GuestOnly guard · AuthLayout) ──────────────────────────────
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  VERIFY_OTP: '/auth/otp-verify',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password/:token',
  LOGOUT: '/auth/logout',

  // ── Customer (Auth + ProfileComplete guards · CustomerLayout) ────────
  CUSTOMER: '/customer',
  DASHBOARD: '/customer/dashboard',
  ONBOARDING: '/customer/onboarding',
  ONBOARDING_STEP: '/customer/onboarding/:step',
  PROFILE: '/customer/profile',
  PROFILE_EDIT: '/customer/profile/edit',
  PROFILE_FINANCIAL: '/customer/profile/financial',
  LIFE_EVENTS: '/customer/life-events',
  LIFE_EVENT_DETAIL: '/customer/life-events/:eventId',
  RECOMMENDATIONS: '/customer/recommendations',
  RECOMMENDATION_DETAIL: '/customer/recommendations/:recId',
  RECOMMENDATION_COMPARE: '/customer/recommendations/compare',
  PRODUCTS: '/customer/products',
  PRODUCT_COMPARE: '/customer/products/compare',
  PRODUCT_DETAIL: '/customer/products/:productId',
  PRODUCT_APPLY: '/customer/products/:productId/apply',
  PRODUCT_CALCULATE: '/customer/products/:productId/calculate',
  APPLICATIONS: '/customer/applications',
  APPLICATION_NEW: '/customer/applications/new',
  APPLICATION_DETAIL: '/customer/applications/:appId',
  APPLICATION_STATUS: '/customer/applications/:appId/status',
  APPLICATION_ACCEPT: '/customer/applications/:appId/accept',
  KYC: '/customer/kyc',
  KYC_UPLOAD: '/customer/kyc/upload',
  KYC_STATUS: '/customer/kyc/status',
  GOALS: '/customer/goals',
  GOAL_NEW: '/customer/goals/new',
  GOAL_DETAIL: '/customer/goals/:goalId',
  GOAL_EDIT: '/customer/goals/:goalId/edit',
  TRANSACTIONS: '/customer/transactions',
  TRANSACTION_DETAIL: '/customer/transactions/:transactionId',
  TRANSACTION_CATEGORIES: '/customer/transactions/categories',
  NOTIFICATIONS: '/customer/notifications',
  NOTIFICATION_DETAIL: '/customer/notifications/:notificationId',
  VOICE: '/customer/voice',
  VOICE_HISTORY: '/customer/voice/history',
  VOICE_PREFERENCES: '/customer/voice/preferences',
  CHAT_CUSTOMER: '/customer/chat',
  SETTINGS: '/customer/settings',
  SETTINGS_NOTIFICATIONS: '/customer/settings/notifications',
  SETTINGS_SECURITY: '/customer/settings/security',
  SETTINGS_LANGUAGE: '/customer/settings/language',
  SETTINGS_THEME: '/customer/settings/theme',

  // ── AI Chat (AuthGuard · CustomerLayout) ─────────────────────────────
  CHAT: '/chat',
  CHAT_CONVERSATION: '/chat/conversations/:conversationId',
  CHAT_AGENT: '/chat/agent/:agentType',

  // ── Admin (Auth + AdminRole guards · AdminLayout) ────────────────────
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_CUSTOMER_DETAIL: '/admin/customers/:customerId',
  ADMIN_CUSTOMER_EDIT: '/admin/customers/:customerId/edit',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_NEW: '/admin/products/new',
  ADMIN_PRODUCT_DETAIL: '/admin/products/:productId',
  ADMIN_PRODUCT_EDIT: '/admin/products/:productId/edit',
  ADMIN_CONFIG: '/admin/config',
  ADMIN_CONFIG_CUSTOMER_TYPES: '/admin/config/customer-types',
  ADMIN_CONFIG_LIFE_EVENTS: '/admin/config/life-events',
  ADMIN_CONFIG_PRODUCTS: '/admin/config/products',
  ADMIN_CONFIG_FEATURE_FLAGS: '/admin/config/feature-flags',
  ADMIN_CAMPAIGNS: '/admin/campaigns',
  ADMIN_CAMPAIGN_NEW: '/admin/campaigns/new',
  ADMIN_CAMPAIGN_DETAIL: '/admin/campaigns/:campaignId',
  ADMIN_CAMPAIGN_EDIT: '/admin/campaigns/:campaignId/edit',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_ANALYTICS_CUSTOMERS: '/admin/analytics/customers',
  ADMIN_ANALYTICS_PRODUCTS: '/admin/analytics/products',
  ADMIN_ANALYTICS_REVENUE: '/admin/analytics/revenue',
  ADMIN_ANALYTICS_CONVERSION: '/admin/analytics/conversion',
  ADMIN_MONITORING: '/admin/monitoring',
  ADMIN_MONITORING_LOGS: '/admin/monitoring/logs',
  ADMIN_MONITORING_PERFORMANCE: '/admin/monitoring/performance',
  ADMIN_MONITORING_ERRORS: '/admin/monitoring/errors',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_REPORT_GENERATE: '/admin/reports/generate',
  ADMIN_REPORT_DETAIL: '/admin/reports/:reportId',
  ADMIN_SETTINGS: '/admin/settings',

  // ── RM (Auth + RMRole guard · RMLayout) ──────────────────────────────
  RM: '/rm',
  RM_DASHBOARD: '/rm/dashboard',
  RM_CUSTOMERS: '/rm/customers',
  RM_CUSTOMER_DETAIL: '/rm/customers/:customerId',
  RM_CUSTOMER_ENGAGE: '/rm/customers/:customerId/engage',
  RM_LEADS: '/rm/leads',
  RM_LEAD_DETAIL: '/rm/leads/:leadId',
  RM_LEAD_CONVERT: '/rm/leads/:leadId/convert',
  RM_TASKS: '/rm/tasks',
  RM_TASK_DETAIL: '/rm/tasks/:taskId',
  RM_CALENDAR: '/rm/calendar',
  RM_APPOINTMENTS: '/rm/calendar/appointments',
  RM_PERFORMANCE: '/rm/performance',
  RM_TARGETS: '/rm/targets',

  // ── Error (BlankLayout) ──────────────────────────────────────────────
  NOT_FOUND: '/404',
  FORBIDDEN: '/403',
  SERVER_ERROR: '/500',
  MAINTENANCE: '/503',
  OFFLINE: '/offline',
  SESSION_EXPIRED: '/session-expired',

  // ── Catch-all ────────────────────────────────────────────────────────
  CATCH_ALL: '*',
} as const;

// Helper builders for parameterized routes
export const routeBuilders = {
  onboardingStep: (step: string) => `/customer/onboarding/${step}`,
  lifeEventDetail: (eventId: string) => `/customer/life-events/${eventId}`,
  recommendationDetail: (recId: string) => `/customer/recommendations/${recId}`,
  productDetail: (productId: string) => `/customer/products/${productId}`,
  productApply: (productId: string) => `/customer/products/${productId}/apply`,
  productCalculate: (productId: string) => `/customer/products/${productId}/calculate`,
  applicationDetail: (appId: string) => `/customer/applications/${appId}`,
  applicationStatus: (appId: string) => `/customer/applications/${appId}/status`,
  applicationAccept: (appId: string) => `/customer/applications/${appId}/accept`,
  goalDetail: (goalId: string) => `/customer/goals/${goalId}`,
  goalEdit: (goalId: string) => `/customer/goals/${goalId}/edit`,
  transactionDetail: (transactionId: string) => `/customer/transactions/${transactionId}`,
  notificationDetail: (notificationId: string) => `/customer/notifications/${notificationId}`,
  chatAgent: (agentType: string) => `/chat/agent/${agentType}`,
  chatConversation: (conversationId: string) => `/chat/conversations/${conversationId}`,
  adminCustomerDetail: (customerId: string) => `/admin/customers/${customerId}`,
  adminCustomerEdit: (customerId: string) => `/admin/customers/${customerId}/edit`,
  adminProductDetail: (productId: string) => `/admin/products/${productId}`,
  adminProductEdit: (productId: string) => `/admin/products/${productId}/edit`,
  adminCampaignDetail: (campaignId: string) => `/admin/campaigns/${campaignId}`,
  adminCampaignEdit: (campaignId: string) => `/admin/campaigns/${campaignId}/edit`,
  adminReportDetail: (reportId: string) => `/admin/reports/${reportId}`,
  rmCustomerDetail: (customerId: string) => `/rm/customers/${customerId}`,
  rmCustomerEngage: (customerId: string) => `/rm/customers/${customerId}/engage`,
  rmLeadDetail: (leadId: string) => `/rm/leads/${leadId}`,
  rmLeadConvert: (leadId: string) => `/rm/leads/${leadId}/convert`,
  rmTaskDetail: (taskId: string) => `/rm/tasks/${taskId}`,
  helpArticle: (articleId: string) => `/help/${articleId}`,
  publicProductDetail: (productId: string) => `/products/${productId}`,
  resetPassword: (token: string) => `/auth/reset-password/${token}`,
};

export type RoutesConfig = typeof ROUTES;

export default ROUTES;
