import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/scroll-animations.css";
import "@/styles/cyber-light-theme.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/server/Navbar";
import ScrollRevealInit from "@/components/ScrollRevealInit";
import DotGridParallax from "@/components/DotGridParallax";

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Enyard Cyber Division",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cn("font-mono", jetbrainsMono.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Navbar />
        {children}
        <ScrollRevealInit />
        <DotGridParallax />
      </body>
    </html>
  );
}
